init:
	cargo new iterators 

test:
	cargo test 

test_2:
	cargo test iterator_sum

test_3:
	cargo test produce_other_iterators

test_4:
	cargo test closure_captures_environment

test_5:
	cargo test create_own_iterator_trait

test_6:
	cargo test using_other_iterator_trait_methods
