init:
	cargo new minigrep 

# run_case_sensitive:
run:
	cargo run to poem.txt > output.txt

run_case_insensitive:
	CASE_INSENSITIVE=1 cargo run to poem.txt 

run_2:
	cargo run frog poem.txt

run_3:
	cargo run body poem.txt

run_4:
	cargo run monomorphization poem.txt

run_error_1:
	cargo run 

run_error_2:
	cargo run the non-file.txt

test:
	cargo test 

